class Calendar{constructor(){this.currentDate=new Date,this.selectedDate=null,this.events=JSON.parse(localStorage.getItem("calendarEvents"))||{},this.lunar=new Lunar,this.init()}init(){this.renderCalendar(),this.bindEvents()}bindEvents(){document.getElementById("prevMonth").addEventListener("click",()=>{this.currentDate.setMonth(this.currentDate.getMonth()-1),this.renderCalendar()}),document.getElementById("nextMonth").addEventListener("click",()=>{this.currentDate.setMonth(this.currentDate.getMonth()+1),this.renderCalendar()}),document.querySelectorAll(".type-btn").forEach(e=>{e.addEventListener("click",e=>{document.querySelectorAll(".type-btn").forEach(e=>e.classList.remove("active")),e.target.classList.add("active"),this.renderCalendar()})}),document.querySelector(".close-btn").addEventListener("click",()=>{document.getElementById("eventModal").style.display="none"}),window.addEventListener("click",e=>{var t=document.getElementById("eventModal");e.target===t&&(t.style.display="none")}),document.getElementById("addEvent").addEventListener("click",()=>{this.showAddEventForm()})}renderCalendar(){var n=this.currentDate.getFullYear(),a=this.currentDate.getMonth(),e=(document.getElementById("currentMonth").textContent=n+`年 ${a+1}月`,new Date(n,a,1)),s=new Date(n,a+1,0).getDate(),t=e.getDay(),r=document.getElementById("calendarDays");r.innerHTML="";for(let e=0;e<t;e++){var d=document.createElement("div");d.className="calendar-day empty",r.appendChild(d)}for(let t=1;t<=s;t++){var l=document.createElement("div");l.className="calendar-day";let e=this.formatDate(n,a+1,t);var i=this.lunar.getLunarDate(n,a+1,t),c=document.createElement("div"),o=(c.className="solar-date",c.textContent=t,document.createElement("div")),m=(o.className="lunar-date",this.lunar.getAllFestivals(n,a+1,t,i)),m=(0<m.length?(o.textContent=m[0],o.classList.add("festival")):o.textContent=i.day,new Date);n===m.getFullYear()&&a===m.getMonth()&&t===m.getDate()&&l.classList.add("today"),this.events[e]&&l.classList.add("has-event"),l.appendChild(c),l.appendChild(o),l.addEventListener("click",()=>this.showEventModal(e)),r.appendChild(l)}}formatDate(e,t,n){return`${e}-${String(t).padStart(2,"0")}-`+String(n).padStart(2,"0")}showEventModal(e){var t=document.getElementById("eventModal"),[n,a,s]=e.split("-").map(Number),r=this.lunar.getLunarDate(n,a,s),d=this.lunar.getAllFestivals(n,a,s,r);document.getElementById("selectedDate").textContent=n+`年${a}月${s}日`,document.getElementById("lunarDate").textContent=r.year+" "+r.month+r.day,document.getElementById("solarTerm").textContent=r.solarTerm||"无",document.getElementById("festivals").textContent=0<d.length?d.join("、"):"无",this.renderEvents(e),t.style.display="block"}showAddEventForm(){let a=document.getElementById("selectedDate").textContent;var e=document.querySelector(".event-form");e&&e.remove();let s=document.createElement("div");s.className="event-form",s.innerHTML=`
            <h4>添加新事件</h4>
            <input type="text" id="eventTitle" placeholder="事件标题" class="event-input">
            <textarea id="eventDesc" placeholder="事件描述" class="event-input"></textarea>
            <div class="event-form-buttons">
                <button class="save-btn">保存</button>
                <button class="cancel-btn">取消</button>
            </div>
        `,document.getElementById("eventsList").appendChild(s),s.querySelector(".save-btn").addEventListener("click",()=>{var e,t=document.getElementById("eventTitle").value.trim(),n=document.getElementById("eventDesc").value.trim();t?(e=this.formatDateFromText(a),this.events[e]||(this.events[e]=[]),this.events[e].push({title:t,desc:n,timestamp:(new Date).getTime()}),localStorage.setItem("calendarEvents",JSON.stringify(this.events)),this.renderEvents(e),this.renderCalendar(),s.remove()):alert("请输入事件标题")}),s.querySelector(".cancel-btn").addEventListener("click",()=>{s.remove()})}formatDateFromText(e){var t,n,a,e=e.match(/(\d+)年(\d+)月(\d+)日/);return e?([t,e,n,a]=e,this.formatDate(e,n,a)):""}renderEvents(a){let s=document.getElementById("eventsList");s.innerHTML="",this.events[a]&&0<this.events[a].length&&this.events[a].forEach((e,t)=>{var n=document.createElement("div");n.className="event-item",n.innerHTML=`
                    <h5>${e.title}</h5>
                    ${e.desc?`<p>${e.desc}</p>`:""}
                    <button class="delete-btn" data-index="${t}">删除</button>
                `,n.querySelector(".delete-btn").addEventListener("click",e=>{e=e.target.dataset.index;this.events[a].splice(e,1),0===this.events[a].length&&delete this.events[a],localStorage.setItem("calendarEvents",JSON.stringify(this.events)),this.renderEvents(a),this.renderCalendar()}),s.appendChild(n)})}getFestivals(e,t){var[,e,n]=e.split("-"),e=this.lunar.festivals.solar[e+"-"+n],n=t.festival,a=[];return e&&a.push(e),n&&a.push(n),t.solarTerm&&a.push(t.solarTerm),a.join("、")}}document.addEventListener("DOMContentLoaded",()=>{new Calendar});