name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g html-minifier-terser
          npm install -g clean-css-cli
          npm install -g uglify-js

      - name: Build and minify
        run: |
          # 创建构建目录
          mkdir -p dist

          # 复制所有文件到构建目录
          cp -r * dist/ 2>/dev/null || :

          # 压缩 HTML 文件
          find dist -name "*.html" -type f -exec html-minifier-terser \
            --collapse-whitespace \
            --remove-comments \
            --remove-optional-tags \
            --remove-redundant-attributes \
            --remove-script-type-attributes \
            --remove-tag-whitespace \
            --use-short-doctype \
            --minify-css true \
            --minify-js true \
            -o {} {} \;

          # 压缩 CSS 文件
          find dist -name "*.css" -type f -exec cleancss -o {} {} \;

          # 压缩 JavaScript 文件
          find dist -name "*.js" -type f -exec uglifyjs {} -c -m -o {} \;

          # 复制必要的文件
          cp README.md dist/ || :
          cp LICENSE dist/ || :

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ${{ secrets.CNAME }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
          full_commit_message: |
            Deploy to GitHub Pages
            
            Triggered by ${{ github.event.head_commit.message }}